Repository OZ-Coding-School/oz_03_collabo-003-FE, pull requests merged in 2024-08, with the labels that each got.

#4 Style: 초기 Css 설정
  .eslintrc.cjs
  src/index.css
  tailwind.config.js
Labels: Style

#7 [Feat] Nav 및 Footer 제작
  public/assets/vite.svg
  public/images/facebook.png
  public/images/instagram.png
  public/images/x.png
  src/Data/categoryData.ts
  src/Data/promoData.ts
  src/components/DropdownMenu.tsx
  src/components/common/button/BtnNav.tsx
  src/components/layout/Footer.tsx
  src/components/layout/NavBar.tsx
  src/index.css
  src/types/type.ts
  tailwind.config.js
Labels: Feat, Style

#8 Feat: 홈페이지 인기있는 플랫폼 파트 UI 디자인
  package-lock.json
  package.json
  src/App.tsx
  src/Data/users.json
  src/components/layout/NavBar.tsx
  src/components/specific/MainPopularCard.tsx
  src/components/specific/MainPopularPlatform.tsx
  src/data/contents.json
  src/index.css
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageOwner.tsx
  src/types/type.ts
  tsconfig.app.json
Labels: Feat

#11 Feat: homePage UI, 기능 추가 및 ci 파일 추가
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/기타-문의.md
  .github/ISSUE_TEMPLATE/새로운-기능-추가.md
  .github/workflows/ci.yml
  postcss.config.js
  public/images/connection-curve.png
  public/images/owner-icon.png
  public/images/possible-1.png
  public/images/possible-2.png
  public/images/possible-3.png
  public/images/possible-4.png
  public/images/provider-icon.png
  public/images/review-profile.png
  public/images/role-admin.png
  public/images/role-provider.png
  public/images/role-user.png
  public/images/shopper-icon.png
  src/Data/contents.json
  src/assets/react.svg
  src/components/DropdownMenu.tsx
  src/components/layout/Footer.tsx
  src/components/specific/MainDescription.tsx
  src/components/specific/MainImageCard.tsx
  src/pages/HomePage.tsx
  src/types/type.ts
Labels: Feat, Chore

#12 lint 설정 변경 및 인기 있는 플랫폼 글씨 크기/색상 조정
  .eslintrc.cjs
  src/components/specific/MainPopularPlatform.tsx
  src/types/type.ts
Labels: Test, Style

#13 lint 설정 변경 및 data 폴더 대소문자 변경으로 인한 error test
  src/data/categoryData.ts
  src/data/contents.json
  src/data/promoData.ts
  src/data/users.json
Labels: Fix, Test, Style

#17 feat: 이용자/의뢰자 마이페이지 사이드바(#15)
  src/components/common/SideBar.tsx
  src/components/common/button/BtnMypage.tsx
  src/data/users.json
  src/pages/MyPage.tsx
  src/pages/MyPageOwner.tsx
  src/types/type.ts
Labels: Feat

#19 Feat/my
  package-lock.json
  package.json
  public/images/google-logo.png
  public/images/kakao-logo.png
  public/images/naver-logo.png
  src/App.tsx
  src/pages/LogInPage.tsx
Labels: Feat

#23 Feat/lint error test
  .eslintrc.cjs
  package-lock.json
  package.json
  src/components/common/button/BtnMypage.tsx
  src/components/specific/MypageOwnerInfo.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageOwner.tsx
Labels: Test

#24 [Feat] 의뢰자 페이지 UI 추가
  README.md
  index.html
  package-lock.json
  package.json
  public/images/point-icon.png
  src/App.tsx
  src/components/common/ModalContainer.tsx
  src/components/common/Pagination.tsx
  src/components/common/button/BtnHeart.tsx
  src/components/layout/Footer.tsx
  src/components/specific/MainDescription.tsx
  src/components/specific/MainImgCard.tsx
  src/components/specific/MyPageAuthz.tsx
  src/components/specific/MyPageCardContainer.tsx
  src/components/specific/MyPageImgCard.tsx
  src/components/specific/MyPageUserInfo.tsx
  src/data/siteCard.json
  src/pages/MyPage.tsx
  src/pages/MyPageOwner.tsx
Labels: Fix, Feat

#26 의뢰자 마이페이지(사이트 관리 조회/수정, 의뢰자 정보 조회)
  src/App.tsx
  src/components/common/SideBar.tsx
  src/components/specific/MyPageCardContainer.tsx
  src/components/specific/MyPageImgCard.tsx
  src/components/specific/MypageOwnerInfo.tsx
  src/components/specific/MypageOwnerItemDetail.tsx
  src/data/content.json
  src/pages/MyPageOwner.tsx
  src/pages/MyPageOwnerSiteDetail.tsx
  src/types/type.ts
Labels: Feat, Other

#30 [Feat] Site등록페이지 / 분석의뢰 신청페이지 UI
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/button/BtnNav.tsx
  src/components/common/button/NavBtn.tsx
  src/components/common/button/PaymentBtn.tsx
  src/components/layout/Footer.tsx
  src/components/layout/NavBar.tsx
  src/components/specific/AnalyzePayMain.tsx
  src/components/specific/NavDropdownMenu.tsx
  src/components/specific/NavMenu.tsx
  src/components/specific/PageEditor.tsx
  src/data/categoryData.ts
  src/data/promoData.ts
  src/data/userGuideData.ts
  src/index.css
  src/pages/SiteRegistrationPage.tsx
  src/types/type.ts
  tailwind.config.js
Labels: Fix, Feat, Style, Chore

#31 [FEAT] 상세 정보 UI 및 일부 기능 추가
  package-lock.json
  package.json
  public/images/new-window-white.png
  public/images/site-sample-img.png
  src/App.tsx
  src/components/common/SelectedBar.tsx
  src/components/common/StarRating.tsx
  src/components/common/TextBoxGray.tsx
  src/components/common/button/BtnHeart.tsx
  src/components/common/button/BtnToggle.tsx
  src/components/specific/DeatailedQnABox.tsx
  src/components/specific/DetailedContents.tsx
  src/components/specific/DetailedReviewBox.tsx
  src/components/specific/DetailedTitle.tsx
  src/data/content.json
  src/data/detailedContents.json
  src/data/detailedInfo.json
  src/pages/DetailedPage.tsx
  src/types/type.ts
Labels: Feat

#33 분석가 마이페이지 신청하기 및 스크롤 버그 관련
  src/App.tsx
  src/components/common/SideBar.tsx
  src/components/common/button/WhiteBtn.tsx
  src/components/specific/MainPopularPlatform.tsx
  src/components/specific/MyPageAnalystAnalysisState.tsx
  src/components/specific/MyPageAuthz.tsx
  src/components/specific/MyPageCardContainer.tsx
  src/components/specific/MyPageOwnerAnalysisRequest.tsx
  src/components/specific/MyPageUserInfo.tsx
  src/components/specific/MypageAnalystApply.tsx
  src/components/specific/MypageOwnerInfo.tsx
  src/components/specific/MypageOwnerItemDetail.tsx
  src/data/contents.json
  src/index.css
  src/pages/AnalystMyPage.tsx
  src/pages/MyPage.tsx
  src/pages/MyPageOwnerSiteDetail.tsx
  src/pages/OwnerMyPage.tsx
  src/pages/OwnerSiteDetailPage.tsx
  src/store/store.tsx
  src/types/type.ts
Labels: Fix, Feat

#35 feat: 로그인페이지 수정, 회원가입 페이지, 비밀번호 찾기 페이지, 회원 탈퇴 페이지 추가
  src/App.tsx
  src/pages/DeleteAccout.tsx
  src/pages/LogInPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/SignUpPage.tsx
Labels: Feat, Other

#37 의뢰자/분석가 매칭, 이미지 로딩 스켈레톤 적용
  src/components/common/LoadingSkeleton.tsx
  src/components/common/button/DisabledBtn.tsx
  src/components/specific/AnalystReportModal.tsx
  src/components/specific/MainPopularPlatform.tsx
  src/components/specific/MyPageAnalystAnalysisState.tsx
  src/components/specific/MyPageAnalystAnalyze.tsx
  src/components/specific/MyPageOwnerAnalysisRequest.tsx
  src/components/specific/MypageAnalystApply.tsx
  src/components/specific/MypageOwnerInfo.tsx
  src/data/analysisContents.json
  src/pages/AnalystMyPage.tsx
  src/pages/OwnerMyPage.tsx
  tailwind.config.js
Labels: Feat

#39 [Feat] 카테고리별 목록UI 제작
  package-lock.json
  src/App.tsx
  src/components/layout/NavBar.tsx
  src/components/specific/NavDropdownMenu.tsx
  src/components/specific/NavMenu.tsx
  src/data/categories.json
  src/data/categoriesContents.json
  src/data/categoryData.ts
  src/data/subCategoriesContents.json
  src/pages/AnalystRequestPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/SiteRegistrationPage.tsx
Labels: Fix, Docs, Feat, Style

#40 [Feat] 분석가 정보 조회 및 수정 UI 업로드
  public/images/complete-icon.png
  src/App.tsx
  src/components/common/ModalContainer.tsx
  src/components/common/ModalMultiStepPermission.tsx
  src/components/specific/MyPageAnalystInfo.tsx
  src/components/specific/MyPageAnalystInfoEdit.tsx
  src/components/specific/MyPageAuthz.tsx
  src/components/specific/MyPageUserInfo.tsx
  src/data/analystProfile.json
  src/index.css
  src/pages/AnalystMyPage.tsx
  src/types/type.ts
Labels: Feat

#41 [Feat] 페이지 등록 페이지 UI 수정 및 제작
  package-lock.json
  src/components/common/AutoResizeTextarea.tsx
  src/components/specific/FileUpload.tsx
  src/pages/SiteRegistrationPage.tsx
Labels: Feat, Chore

#42 feat: 변경된 api 반영하여 기능 추가, 코드 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/specific/PrivateRoute.tsx
  src/pages/DeleteAccout.tsx
  src/pages/LogInPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/SignUpPage.tsx
  src/store/store.tsx
Labels: Feat, Style, Other

#43 의뢰자 - 분석가 선택시 프로필 열람 기능 추가
  src/components/specific/MyPageOwnerAnalysisRequest.tsx
Labels: Feat

#48 Chore: build yml 파일 추가
  .github/workflows/front-build.yml
Labels: Chore

#49 Feat: 분석의뢰-결제기능 연결
  .github/workflows/front-build.yml
  src/App.tsx
  src/components/specific/FileUpload.tsx
  src/components/specific/PaymentSection.tsx
  src/pages/AnalystRequestPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/SiteRegistrationPage.tsx
Labels: Docs, Feat, Style, Chore

#50 Merge
  .github/workflows/front-build.yml
  src/App.tsx
  src/components/specific/FileUpload.tsx
  src/components/specific/PaymentSection.tsx
  src/pages/AnalystRequestPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/SiteRegistrationPage.tsx
Labels: Chore

#51 Feat: 스토어에 유저정보 추가. 소셜로그인 리다이렉션 페이지 추가, 회원가입 이메일 인증 방식 변경, 변경된 api 적용(test api)
  src/App.tsx
  src/pages/DeleteAccout.tsx
  src/pages/LogInPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/RedirectHandlerPage.tsx
  src/pages/SignUpPage.tsx
  src/store/store.tsx
Labels: Feat, Style

#52 style: 비밀번호 찾기, 회원가입 인증 버튼 UI 수정, 소셜로그인 이미지 호버 효과 추가
  src/pages/LogInPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/SignUpPage.tsx
Labels: Style

#53 Feat: 스토어에서 유저 정보를 로컬스토리지에 저장하도록 수정, 비밀번호 시각화 기능 추가
  package-lock.json
  package.json
  src/pages/LogInPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/SignUpPage.tsx
  src/store/store.tsx
Labels: Feat

#54 SEO를 위한 meta tag 적용
  index.html
  public/robots.txt
  src/components/specific/AnalystReportModal.tsx
  src/components/specific/MainPopularCard.tsx
  src/components/specific/MainPopularPlatform.tsx
  src/components/specific/MyPageAnalystAnalyze.tsx
  src/components/specific/MyPageOwnerAnalysisRequest.tsx
  src/components/specific/MypageAnalystApply.tsx
  src/components/specific/MypageOwnerItemDetail.tsx
  src/data/content.json
  src/data/contents.json
  src/pages/OwnerSiteDetailPage.tsx
  src/types/type.ts
Labels: Feat

#56 로컬 개발환경에 HTTPS 적용하기
  .gitignore
  package-lock.json
  package.json
  vite.config.ts
Labels: Feat

#57 [Feat] Nav 로그아웃 추가
  src/components/common/button/NavBtn.tsx
  src/components/layout/Footer.tsx
  src/components/layout/NavBar.tsx
  src/pages/AnalystRequestPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/SiteRegistrationPage.tsx
  tailwind.config.js
Labels: Docs, Feat, Style

#58 Feat: 비밀번호 찾기 페이지에 로직 추가
  package-lock.json
  src/pages/PasswordResetPage.tsx
Labels: Feat

#59 [Feat] Nav - 모바일 NavMenu 제작
  src/components/layout/NavBar.tsx
  src/components/specific/NavMobileMenu.tsx
Labels: Feat

#60 Fix: 배포된 백엔드 api 반영, 에러 해결
  src/components/layout/NavBar.tsx
  src/pages/DeleteAccout.tsx
  src/pages/LogInPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/RedirectHandlerPage.tsx
  src/pages/SignUpPage.tsx
  src/store/store.tsx
Labels: Fix, Feat, Style
