Repository OZ-Coding-School/oz_03_collabo-003-FE, pull requests merged in 2024-09, with the labels that each got.

#61 [Feat] api 및 service 제작
  src/App.tsx
  src/apis/api/analyst.ts
  src/apis/api/auth.ts
  src/apis/api/authSocial.ts
  src/apis/api/categories.ts
  src/apis/api/content.ts
  src/apis/api/likeContent.ts
  src/apis/api/payment.ts
  src/apis/api/request.ts
  src/apis/api/reviewContent.ts
  src/apis/services/categoryContentService.ts
  src/apis/services/categoryService.ts
  src/apis/services/contentService.ts
  src/apis/utils/instance.ts
  src/components/layout/NavBar.tsx
  src/components/specific/NavMenu.tsx
  src/components/specific/NavMobileMenu.tsx
  src/data/categories.json
  src/data/contents_v2.json
  src/data/semiCategoriesContents.json
  src/pages/CategoryPage.tsx
  src/pages/SiteRegistrationPage.tsx
  src/types/type.ts
Labels: Docs, Test, Feat, Style

#62 Merge
  .gitignore
  index.html
  package-lock.json
  package.json
  public/robots.txt
  src/App.tsx
  src/apis/api/analyst.ts
  src/apis/api/auth.ts
  src/apis/api/authSocial.ts
  src/apis/api/categories.ts
  src/apis/api/content.ts
  src/apis/api/likeContent.ts
  src/apis/api/payment.ts
  src/apis/api/request.ts
  src/apis/api/reviewContent.ts
  src/apis/services/categoryContentService.ts
  src/apis/services/categoryService.ts
  src/apis/services/contentService.ts
  src/apis/utils/instance.ts
  src/components/common/button/NavBtn.tsx
  src/components/layout/Footer.tsx
  src/components/layout/NavBar.tsx
  src/components/specific/AnalystReportModal.tsx
  src/components/specific/MainPopularCard.tsx
  src/components/specific/MainPopularPlatform.tsx
  src/components/specific/MyPageAnalystAnalyze.tsx
  src/components/specific/MyPageOwnerAnalysisRequest.tsx
  src/components/specific/MypageAnalystApply.tsx
  src/components/specific/MypageOwnerItemDetail.tsx
  src/components/specific/NavMenu.tsx
  src/components/specific/NavMobileMenu.tsx
  src/data/categories.json
  src/data/content.json
  src/data/contents.json
  src/data/contents_v2.json
  src/data/semiCategoriesContents.json
  src/pages/AnalystRequestPage.tsx
  src/pages/CategoryPage.tsx
  src/pages/DeleteAccout.tsx
  src/pages/LogInPage.tsx
  src/pages/OwnerSiteDetailPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/RedirectHandlerPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/SiteRegistrationPage.tsx
  src/store/store.tsx
  src/types/type.ts
  tailwind.config.js
  vite.config.ts
Labels: Chore

#64 회원가입 페이지 axios 에러 해결
  src/pages/LogInPage.tsx
  src/pages/SignUpPage.tsx
Labels: Fix

#65 Feat: 로그인 실패 시 에러 문구 띄우는 로직 수정, 인증 완료 시 인풋 비활성화
  src/pages/LogInPage.tsx
  src/pages/SignUpPage.tsx
Labels: Feat

#66 Merge
  src/pages/LogInPage.tsx
  src/pages/SignUpPage.tsx
Labels: Chore

#67 [Chore] Build 파일에 env 환경변수 추가
  .github/workflows/front-build.yml
  src/components/layout/NavBar.tsx
Labels: Chore

#68 Feat: 유효성 검사 등 일부 기능 추가 및 UI 변경
  src/components/common/ModalMultiStep.tsx
  src/components/specific/MyPageAnalystInfoEdit.tsx
  src/components/specific/MyPageAuthz.tsx
  src/components/specific/MyPageUserInfo.tsx
  src/data/analystProfile.json
Labels: Fix, Feat, Style

#70 Feat: 소셜로그인 성공, 실패 시 alert 추가, 닉네임 유효성 검사 추가 및 비밀번호 유효성 검사 수정
  src/pages/RedirectHandlerPage.tsx
  src/pages/SignUpPage.tsx
Labels: Feat

#71 Merge
  src/components/common/ModalMultiStep.tsx
  src/components/specific/MyPageAnalystInfoEdit.tsx
  src/components/specific/MyPageAuthz.tsx
  src/components/specific/MyPageUserInfo.tsx
  src/data/analystProfile.json
  src/pages/RedirectHandlerPage.tsx
  src/pages/SignUpPage.tsx
Labels: Chore

#72 Feat: 소셜로그인 리다이렉트 페이지, 비밀번호 찾기 페이지 수정
  src/pages/PasswordResetPage.tsx
  src/pages/RedirectHandlerPage.tsx
Labels: Fix

#73 Merge
  src/pages/PasswordResetPage.tsx
  src/pages/RedirectHandlerPage.tsx
Labels: Chore

#74 Fix: 소셜로그인 알림이 뜨도록 수정
  src/pages/RedirectHandlerPage.tsx
Labels: Fix

#75 Merge
  src/pages/RedirectHandlerPage.tsx
Labels: Chore

#76 소셜로그인 절대 경로로 설정
  src/pages/LogInPage.tsx
Labels: Fix

#77 Fix: 이메일을 로컬스토리지가 저장하는 것이 아닌 쿼리 파라미터로 받아서 추출하는 방식으로 변경
  src/pages/LogInPage.tsx
  src/pages/PasswordResetPage.tsx
Labels: Fix

#79 로컬스토지에 이메일 저장
  src/pages/PasswordResetPage.tsx
Labels: Fix

#80 Merge
  src/pages/PasswordResetPage.tsx
Labels: Chore

#81 분석가 보고서 진행 전/완료 구분 및 UI 개선
  src/apis/api/auth.ts
  src/apis/api/content.ts
  src/components/common/SideBar.tsx
  src/components/specific/AnalystReportModal.tsx
  src/components/specific/MainPopularPlatform.tsx
  src/components/specific/MyPageAnalystAnalyze.tsx
  src/components/specific/MyPageAnalystInfo.tsx
  src/components/specific/MyPageImgCard.tsx
  src/components/specific/MyPageOwnerAnalysisRequest.tsx
  src/components/specific/MyPageUserInfo.tsx
  src/components/specific/MypageAnalystApply.tsx
  src/components/specific/MypageOwnerInfo.tsx
  src/data/analysisContents.json
  src/data/analystProfile.json
  src/data/content.json
  src/data/contents.json
  src/data/siteCard.json
  src/data/users.json
  src/pages/OwnerSiteDetailPage.tsx
  src/types/type.ts
Labels: Feat, Style

#83 [Docs] Content 더미데이터 수정
  src/apis/api/content.ts
  src/apis/services/categoryContentService.ts
  src/data/categoriesContents.json
  src/data/contents.json
  src/data/contents_V2.json
  src/pages/CategoryPage.tsx
Labels: Docs

#84 Feat/edit UI
  src/components/common/SideBar.tsx
  src/components/specific/MainPopularPlatform.tsx
  src/data/analysisContents.json
  src/data/content.json
  src/data/contents.json
  src/types/type.ts
Labels: Docs, Style

#85 Style: 비밀번호 시각화 UI 수정
  src/pages/LogInPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/SignUpPage.tsx
Labels: Style

#86 Design/nav
  src/components/layout/NavBar.tsx
  src/components/specific/NavMenu.tsx
  src/components/specific/NavMobileMenu.tsx
  tailwind.config.js
Labels: Fix, Style

#87 Style: 반응형 추가 및 UI 수정
  src/components/common/button/BtnHeart.tsx
  src/components/specific/MyPageAuthz.tsx
  src/components/specific/MyPageImgCard.tsx
  src/components/specific/MyPageUserInfo.tsx
  src/data/analystProfile.json
  src/data/siteCard.json
Labels: Style

#89 [Docs] 주석삭제
  src/components/layout/NavBar.tsx
  tailwind.config.js
Labels: Docs

#91 [Fix]
  src/components/layout/NavBar.tsx
Labels: Fix, Bug

#94 Merge
  src/components/layout/NavBar.tsx
Labels: Chore

#95 Feat: 비밀번호 찾기 페이지 로직 수정, assets/images에 이미지 추가
  src/assets/images/Google Analytics.png
  src/assets/images/HRD-net.png
  src/assets/images/Khan Academy.png
  src/assets/images/LinkedIn Learning.png
  src/assets/images/Stable Diffusion.png
  src/assets/images/ahrefs.png
  src/assets/images/airtable.png
  src/assets/images/all con.png
  src/assets/images/aness.png
  src/assets/images/asana.png
  src/assets/images/chatGPT.png
  src/assets/images/coursera.png
  src/assets/images/edX.png
  src/assets/images/figma.png
  src/assets/images/google ads.png
  src/assets/images/hugging face.png
  src/assets/images/midjourney.png
  src/assets/images/naimy.png
  src/assets/images/notion.png
  src/assets/images/perplexity.png
  src/assets/images/pixabay.png
  src/assets/images/semrush.png
  src/assets/images/slack.png
  src/assets/images/trello.png
  src/assets/images/udemy.png
  src/assets/images/wanted.png
  src/assets/images/국민취업지원제도.png
  src/assets/images/보너스잡.png
  src/assets/images/보조금통합포털.png
  src/assets/images/아이돌봄서비스.png
  src/pages/PasswordResetPage.tsx
Labels: Fix, Other

#96 Merge
  src/assets/images/Google Analytics.png
  src/assets/images/HRD-net.png
  src/assets/images/Khan Academy.png
  src/assets/images/LinkedIn Learning.png
  src/assets/images/Stable Diffusion.png
  src/assets/images/ahrefs.png
  src/assets/images/airtable.png
  src/assets/images/all con.png
  src/assets/images/aness.png
  src/assets/images/asana.png
  src/assets/images/chatGPT.png
  src/assets/images/coursera.png
  src/assets/images/edX.png
  src/assets/images/figma.png
  src/assets/images/google ads.png
  src/assets/images/hugging face.png
  src/assets/images/midjourney.png
  src/assets/images/naimy.png
  src/assets/images/notion.png
  src/assets/images/perplexity.png
  src/assets/images/pixabay.png
  src/assets/images/semrush.png
  src/assets/images/slack.png
  src/assets/images/trello.png
  src/assets/images/udemy.png
  src/assets/images/wanted.png
  src/assets/images/국민취업지원제도.png
  src/assets/images/보너스잡.png
  src/assets/images/보조금통합포털.png
  src/assets/images/아이돌봄서비스.png
  src/pages/PasswordResetPage.tsx
Labels: Chore

#97 Fix: 오류메세지와 오류 코드 수정
  src/pages/PasswordResetPage.tsx
Labels: Fix

#98 Merge
  src/pages/PasswordResetPage.tsx
Labels: Chore

#99 Fix: /accounts/password-reset/confirm/로 보내는 정보에서 이메일 제거
  src/pages/PasswordResetPage.tsx
Labels: Fix

#100 Merge
  src/pages/PasswordResetPage.tsx
Labels: Chore

#101 Fix: /accounts/password-reset/confirm로 요청을 보낼 때, 토큰 전달 방식 수정
  src/pages/PasswordResetPage.tsx
Labels: Fix

#103 data 변경 에 따른 로직 일부 수정
  public/images/thumbnail-HRD-net.png
  public/images/thumbnail-bonusjob.png
  public/images/thumbnail-pixabay.png
  src/components/common/SideBar.tsx
  src/components/specific/MainPopularCard.tsx
  src/components/specific/MainPopularPlatform.tsx
  src/components/specific/MyPageAnalystAnalyze.tsx
  src/components/specific/MyPageAnalystInfo.tsx
  src/components/specific/MyPageAnalystInfoEdit.tsx
  src/components/specific/MyPageCardContainer.tsx
  src/components/specific/MyPageOwnerAnalysisRequest.tsx
  src/components/specific/MypageOwnerInfo.tsx
  src/components/specific/MypageOwnerItemDetail.tsx
  src/data/analysisContents.json
  src/data/analystProfile.json
  src/data/content.json
  src/data/contents.json
  src/pages/AnalystMyPage.tsx
  src/pages/MyPage.tsx
  src/pages/OwnerMyPage.tsx
  src/types/type.ts
Labels: Style, Refactor

#104 Feat: 일부 기능, UI, 데이터 변경
  src/components/specific/DeatailedQnABox.tsx
  src/components/specific/DetailedContents.tsx
  src/components/specific/DetailedReviewBox.tsx
  src/components/specific/DetailedTitle.tsx
  src/components/specific/MyPageCardContainer.tsx
  src/components/specific/MyPageImgCard.tsx
  src/components/specific/MyPageUserInfo.tsx
  src/data/detailedContents.json
  src/pages/DetailedPage.tsx
Labels: Feat, Style
